- id: '1677929309149'
  alias: Lumière Escalier R+1 Salon -> Bibliothèque
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.escalier_r_1_channel_2_input_2
    from: 'on'
    to: 'off'
  - platform: state
    entity_id:
    - binary_sensor.escalier_r_1_channel_2_input_2
    from: 'off'
    to: 'on'
  action:
  - type: toggle
    device_id: 149d51d61a6a95e06a105c487509dab8
    entity_id: light.bibliotheque_cathedrale
    domain: light
  mode: single
- id: '1677929359357'
  alias: Lumière Escalier R+1 Bibliothèque -> Salon
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.escalier_r_1_channel_1_input_2
    from: 'on'
    to: 'off'
  - platform: state
    entity_id:
    - binary_sensor.escalier_r_1_channel_1_input_2
    from: 'off'
    to: 'on'
  action:
  - type: toggle
    device_id: db3ae4fe2527a57e839c9cb43003dff5
    entity_id: 3ce8f89cb7bc1e3aa3e5ea62996ebc5b
    domain: light
  mode: single
- id: '1677929669279'
  alias: Lumière Couloir R-1 Bis
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.couloir_r_1_bis_input
    from: 'on'
    to: 'off'
  - platform: state
    entity_id:
    - binary_sensor.couloir_r_1_bis_input
    from: 'off'
    to: 'on'
  action:
  - type: toggle
    device_id: 66e19625d489beea671ec75d3a52ee72
    entity_id: switch.couloir_r_1_spots
    domain: switch
  mode: single
- id: '1678737818325'
  alias: Thermostat Salon - too hot
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ht_salon_temperature
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: input_number.temperature_salon
  condition: []
  action:
  - type: turn_off
    device_id: 3f41022a06297022401187172974fd47
    entity_id: switch.thermostat_salon
    domain: switch
  - type: turn_off
    device_id: 3f41022a06297022401187172974fd47
    entity_id: switch.thermostat_cuisine
    domain: switch
  - type: turn_off
    device_id: 011b1032ed1708b1a37a61794758f35a
    entity_id: switch.thermostat_entree
    domain: switch
  mode: single
- id: '1678737940785'
  alias: Thermostat Salon - too cold
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ht_salon_temperature
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: input_number.temperature_salon
  condition: []
  action:
  - type: turn_on
    device_id: 3f41022a06297022401187172974fd47
    entity_id: switch.thermostat_salon
    domain: switch
  - type: turn_on
    device_id: 3f41022a06297022401187172974fd47
    entity_id: switch.thermostat_cuisine
    domain: switch
  - type: turn_on
    device_id: 011b1032ed1708b1a37a61794758f35a
    entity_id: switch.thermostat_entree
    domain: switch
  mode: single
- id: '1678997693833'
  alias: Termostat Cabinet - too cold
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ht_cabinet_temperature
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: input_number.temperature_cabinet
  condition: []
  action:
  - type: turn_on
    device_id: 44274be303a9935e703473e58942b19d
    entity_id: switch.thermostat_cabinet
    domain: switch
  mode: single
- id: '1678997797591'
  alias: Thermostat Cabinet - too hot
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ht_cabinet_temperature
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: input_number.temperature_cabinet
  condition: []
  action:
  - type: turn_off
    device_id: 44274be303a9935e703473e58942b19d
    entity_id: switch.thermostat_cabinet
    domain: switch
  mode: single
- id: '1678997936932'
  alias: Thermostat Chambre R-1 - too cold
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ht_chambre_r_1_temperature
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: input_number.temperature_chambre_r_1
  condition: []
  action:
  - type: turn_on
    device_id: 11eb453f4711d9f227584a495a813de2
    entity_id: switch.thermostat_chambre_r_1_m
    domain: switch
  - type: turn_on
    device_id: 11eb453f4711d9f227584a495a813de2
    entity_id: switch.thermostat_chambre_r_1_e
    domain: switch
  mode: single
- id: '1678997989687'
  alias: Thermostat Chambre R-1 - too hot
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ht_chambre_r_1_temperature
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: input_number.temperature_chambre_r_1
  condition: []
  action:
  - type: turn_off
    device_id: 11eb453f4711d9f227584a495a813de2
    entity_id: switch.thermostat_chambre_r_1_m
    domain: switch
  - type: turn_off
    device_id: 11eb453f4711d9f227584a495a813de2
    entity_id: switch.thermostat_chambre_r_1_e
    domain: switch
  mode: single
- id: '1679000159115'
  alias: I4 2 - Réveil
  description: ''
  trigger:
  - platform: device
    device_id: 630901237a01ee2c4bd9a260a464f85e
    domain: shelly
    type: single_push
    subtype: button2
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.reveil
    metadata: {}
  mode: single
- id: '1679000187574'
  alias: I4 1 - Soirée
  description: ''
  trigger:
  - platform: device
    device_id: 630901237a01ee2c4bd9a260a464f85e
    domain: shelly
    type: single_push
    subtype: button1
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.soiree
    metadata: {}
  mode: single
- id: '1683353939470'
  alias: I4 4 - Jour été
  description: ''
  trigger:
  - platform: device
    device_id: 630901237a01ee2c4bd9a260a464f85e
    domain: shelly
    type: single_push
    subtype: button4
  condition: []
  action:
  - service: script.jour_ete
    data: {}
  mode: single
- id: '1684869068331'
  alias: I4 3 - Nuit été
  description: ''
  trigger:
  - platform: device
    device_id: 630901237a01ee2c4bd9a260a464f85e
    domain: shelly
    type: single_push
    subtype: button3
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.nuit_ete
    metadata: {}
  mode: single
