# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
# https://www.home-assistant.io/integrations/frontend/
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/querySelectorDeep.js
    - /local/external-links.js

# https://www.home-assistant.io/lovelace/
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/my-cards/my-cards.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
modbus: !include_dir_list modbus/
template: !include_dir_list templates/
input_boolean: !include helpers/input_boolean.yaml
input_datetime: !include helpers/input_datetime.yaml

panel_custom:
  - name: panel_unifi
    sidebar_title: Unifi
    sidebar_icon: mdi:web
    url_path: "unifi"
    module_url: /local/panel-redirect.js
    embed_iframe: false
    require_admin: true
    config:
      target: https://homeassistant.local:8443/
  - name: panel_vacuum
    sidebar_title: Vacuum
    sidebar_icon: mdi:robot-vacuum
    url_path: "vacuum"
    module_url: /local/panel-redirect.js
    embed_iframe: false
    require_admin: true
    config:
      target: http://valetudo-lonelygleefulmink.local/

logger:
  default: warning
  logs:
    homeassistant.components.modbus: debug
    pymodbus: debug
