# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
# https://www.home-assistant.io/integrations/frontend/
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/querySelectorDeep.js

# https://www.home-assistant.io/lovelace/
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/my-cards/my-cards.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml

panel_custom:
  - name: panel_unifi
    sidebar_title: Unifi
    sidebar_icon: mdi:web
    url_path: "unifi"
    module_url: /api/hassio/app/entrypoint.js
    embed_iframe: true
    require_admin: true
  - name: panel_vacuum
    sidebar_title: Vacuum
    sidebar_icon: mdi:robot-vacuum
    url_path: "vacuum"
    module_url: /api/hassio/app/entrypoint.js
    embed_iframe: true
    require_admin: true
